# 28 numpy exercises

This is a collection of exercises that have been collected in the numpy.

#### 1. Create a null vector of size 10 (★☆☆)

In [2]:
import numpy as np
arr = np.zeros(10)


#### 2.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
arr[5]=1

#### 3.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
arr = np.arange(10, 49)

#### 4.  Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
arr_reverse = arr[::-1]

#### 5.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
arr=np.random.randint(0,8,(3,3))

#### 6. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [ ]:
arr=np.array([1,2,0,0,4,0])
print(np.nonzero(arr))

#### 7. Create a 3x3 identity matrix (★☆☆)

In [ ]:
arr = np.eye(3)

#### 8. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
arr=np.array(np.random.randint(0,10000,(3,3,3)))

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
arr = np.random.random((5,5))
print(arr)
print(np.min(arr))
print(np.max(arr))

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
arr = np.array(np.random.random(30))
print(arr)
print(np.mean(arr))

#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
x[1:-1,1:-1] = 0 #important --->>>>>>>>>>>>>>>>>

#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
np.pad(arr, pad_width=1) #------>>

#### 13. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [36]:
#1 upper 0 lower diag
arr=np.diag(np.arange(4),k=1)
print(arr)

[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 2 0]
 [0 0 0 0 3]
 [0 0 0 0 0]]


#### 14. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [39]:
arr= np.zeros((8,8),dtype=int) ############-->>>.
arr[1::2,::2]=1
print(arr)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


#### 15. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
 np.dot(np.ones((5,3)), np.ones((3,2)))

#### 15. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [3]:
arr = np.arange(11)
x=(arr>3)&(arr<8)
arr[x]*=-1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 16. How to find common values between two arrays? (★☆☆)

In [ ]:
np.intersect1d(ar1, ar2) #--------->>>>>>>>>>>>>>>>>>>>.

#### 17. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [5]:
arr= np.zeros((5,5))
arr+=np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 18. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
arr = np.random.radint(10)
arr.sort()

#### 19. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
np.allclose(A, B) #------->>>>>>>>>>>>>>>>>>>

#### 20. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [11]:
arr= np.random.random(10)
arr[arr.argmax()] = 0
print(arr)

[0.4617973  0.32579401 0.6164936  0.06487492 0.26167077 0.27921824
 0.38176169 0.         0.9058602  0.27354367]


#### 21. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 22. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [23]:
#uniform-->return the random samples as numpy array
x=np.arange(100)
y=np.random.uniform(0,100)
z=(np.abs(x-y)).argmin()
print(x[z])

48


#### 23. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
#################


#### 24. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 25. Subtract the mean of each row of a matrix (★★☆)

In [21]:
#keepdims--->>>>enables you to control the dimensions of the output
arr=np.random.rand(5,10)
sub=arr-arr.mean(axis=1,keepdims=True)
print(sub)

[[ 0.27227229  0.24133415 -0.02099357 -0.02736603 -0.43641007  0.03620031
  -0.33894943  0.32915934 -0.23254273  0.17729574]
 [ 0.12049813  0.36682971  0.36009018 -0.29876139  0.35257827 -0.34274042
  -0.51190452  0.26790022 -0.50276436  0.18827418]
 [-0.22922619 -0.46954653  0.40543619  0.21826742  0.50585192 -0.45592063
   0.35096446 -0.28662513 -0.45906809  0.41986657]
 [-0.18282772  0.03414589  0.33496058  0.09823138 -0.4184589   0.25619469
   0.16279526 -0.3164249  -0.34240077  0.37378448]
 [ 0.28412414 -0.30573978 -0.53163328  0.18423142 -0.04760866  0.34555008
  -0.0229665  -0.20592826  0.19038975  0.10958108]]


#### 26. How to get the diagonal of a dot product? (★★★)

In [27]:
arr1=np.random.randn(100,200)
arr2=np.random.randn(200,200)
diagonal=np.diag(np.dot(arr1,arr2))
print(diagonal)

[ 2.54133536e-01 -1.21936625e+01  1.33261245e+01 -1.36289171e+00
  2.13149888e-01  7.93462445e+00  1.42314072e+01  6.90186901e+00
  4.21419651e+00 -1.33419190e+00  4.46594598e+00 -7.26754950e+00
  7.18977807e-01 -3.90218834e+01  7.16358958e+00 -2.08217488e+00
  6.78795492e+00 -2.22282882e+01 -2.26685740e+01  1.24039440e+01
 -7.29070784e+00 -1.96136692e+01 -3.31465575e+01 -6.52259456e+00
 -2.59680766e+00 -1.39404976e+01 -2.04559065e+01  7.17447272e+00
 -7.76185053e+00 -7.11545046e+00 -1.16191273e+01  1.09632045e+01
  1.25731951e+01  3.37896597e+00 -8.19917944e+00 -5.68924851e+00
  1.02089204e+00 -3.91683086e-01 -5.90832151e+00  5.86710868e+00
 -1.15390299e+01 -1.90892944e+01  1.83006343e+01  1.67959113e+01
 -1.06302460e+01  5.74152464e+00  1.54709433e+00  1.61553258e+01
  2.99300516e+01 -1.64982124e+01  1.60186947e+01 -6.22426053e+00
  1.99564671e-04  1.68792352e+01  1.55907401e+01 -1.00351403e+01
  1.58044857e+01 -3.18336738e+01  1.45916391e+01 -1.74402853e+01
  3.03423230e+01 -1.76688

#### 27. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [30]:
arr=np.array([1,2,3,4,5])
x=3
new_arr=np.zeros(len(arr)+(len(arr)-1)*x)
new_arr[::x+1]=arr #############-->>>>>>
print(new_arr)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 28. How to swap two rows of an array? (★★★)

In [31]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr[[0,1]]=arr[[1,0]]
print(arr)

[[5 6 7 8]
 [1 2 3 4]]
